name: gato_id_generator
description: "Generate id card... But for cats!"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.1+1

#
# ======================================================================================================
#

environment:
  sdk: ">=3.4.5 <4.0.0"

#
# ======================================================================================================
#

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^2.5.0

  # App information provider.
  package_info_plus: ^8.1.0

  # Handles version check.
  version: ^3.0.2

  # Helpful native platform directory path provider
  path_provider: ^2.1.5

  # Handy app's flavor utility.
  # flutter_flavorizr: ^2.2.3

  # Splash screen customization.
  flutter_native_splash: ^2.4.1

  # App icon customization.
  # flutter_launcher_icons: ^0.14.1

  # Easy to use package name changer.
  # change_app_package_name: ^1.3.0

  # Easy app renaming.
  # rename_app: ^1.6.2

  # Time utility.
  intl: ^0.19.0

  # Localization utility.
  easy_localization: ^3.0.7+1
  flutter_string_extractor: ^1.1.2

  # Local database/storage utility.
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

  # Handy collection library
  collection: ^1.19.0

  # Powerful state management solution.
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Dependency injection utility
  get_it: ^8.0.3

  # App routing.
  go_router: ^14.6.1
  go_transitions: ^0.8.0

  # Native share link functionality.
  share_plus: ^10.0.0

  # Native url launcher functionality.
  url_launcher: ^6.3.0

  # Handle network requests.
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0

  # Easy and efficient way to check internet connection.
  internet_connection_checker_plus: ^2.5.0

  # Prevent user to close the app when tapping back button.
  double_back_to_close_app: ^2.1.0

  # App theme font customization.
  google_fonts: ^6.2.1

  # Decorations
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  simple_gradient_text: ^1.3.0
  marqueer: ^2.0.1

  # README badge.
  test_coverage_badge: ^0.3.2

  # Generate fake data
  faker: ^2.2.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # Generate Gato Id utility
  cached_network_image: ^3.4.1
  widgets_to_image: ^1.0.0
  permission_handler: ^12.0.0+1
  image_gallery_saver_plus: ^4.0.1
  flutter_image_converter: ^0.4.1

#
# ======================================================================================================
#

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  # Cool & Useful codegen
  build_runner: ^2.4.15

  # Lints
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0

  # For hive noSQL db.
  hive_ce_generator: ^1.8.1

  # For testing.
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  test: ^1.25.8

#
# ======================================================================================================
#

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/translations/
    - assets/images/splash/
    - assets/images/id/
    - assets/images/contact/
    - assets/images/icon/
    - assets/images/gato/
